<a href="https://colab.research.google.com/github/Prasadkpd/Machine-Learning/blob/master/Train_Test_Split/Train_Test_Split.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
from sklearn.model_selection import train_test_split

In [4]:
x = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]) 
y = np.array([0,0,1,0,1,0,0,0,0,0,1,1,1,0,1,0,1,1,1,1])

In [7]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)

In [9]:
x_train

array([19,  1,  9,  2, 13,  8, 11, 10, 15,  3, 16, 12, 14, 18,  7,  6])

In [10]:
len(x_train)

16

*By adding the random_state with a number we can make the training set is permanent*

In [27]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state=1)

In [28]:
x_train

array([ 3, 15,  5, 18,  8,  2, 14,  1, 20, 19, 10, 16,  9, 13, 12,  6])

In [13]:
len(x_train)

16

*To get the test set in order we have to change the suffle argument to false*

In [29]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, shuffle=False)

In [30]:
x_train

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [31]:
len(x_train)

16